### ISSUE TITLE
addEventListener('change') event not fired for <select> tag

### ISSUE THREAD

**Issue by thdoan** [silviomoreto/bootstrap-select#1027]
I added a 'change' event handler for the `<select>` tag. When the user selects from the Bootstrap-select element, the source `<select>` is also changed, but the 'change' event is not fired.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by thdoan** [comment]
Here's a fiddle: http://jsfiddle.net/10basetom/0m6abfhy/

I have unhidden the native `select` element. If you change the `select` element, then both event handlers are called. However, if you change the Bootstrap-select element, then only the jQuery event handler is called (the 'change' event registered using `addEventListener()` is never fired).

One fix would be to replace `that.$element.change();` on line 1046 with this:

`that.$element[0].dispatchEvent(new Event('change'));`

Now the 'change' event is properly fired regardless of whether you use jQuery or vanilla JS to register it, as demonstrated here: http://jsfiddle.net/10basetom/21wfkmdL/

Note that the `new Event()` constructor is not supported in IE, so if you want IE support then you can create the event the [old-fashioned way](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way).

**Comment by chanjarster** [comment]
Yeah, that's true. I also meet the same problem with jquery-validation plugin.

Here is the fiddle: http://jsfiddle.net/tpe1wLyc/2/

Steps of reproducing:

1. don't select anything and click the submit button
2. jquery validation shows the error message
3. change the native select and blur the error message dismissed
4. change the bootstrap select and blur error message is still there

So I guess the problem is caused by bootstrap-select doesn't fire the 'change' event ( properly ).

Please consider IE8 when fix this bug.

Thanks you very much.
