### ISSUE TITLE
Would you support angularjs please?

### ISSUE THREAD

**Issue by WalterInSH** [silviomoreto/bootstrap-select#1048]
Would you support angularjs in the future please? 
This would be awesome!

**Comment by caseyjhol** [comment]
Check out https://github.com/joaoneto/angular-bootstrap-select. I had to make a few tweaks to get it to work for my needs.

**Comment by WalterInSH** [comment]
@caseyjhol That's really a cool project. I've run the demo, and it worked perfectly! Thanks!

**Comment by m3Lith** [comment]
@caseyjhol Would you mind yo elaborate on what did you tweak? Personally, I've found out that it slows down laoding of the page quite significantly if there're a lot of options (I have ~200, used in combination with data-live-search).

**Comment by caseyjhol** [comment]
I'm still in the process of developing it, but I forked angular-bootstrap-select due to inactivity from the developer. [ng-bootstrap-select](https://github.com/caseyjhol/ng-bootstrap-select). In my implementation, I'm utilizing `render` instead of `refresh` when only the model is being updated. I'm also using a custom attribute that allows me to use ngRepeat instead of ngOptions for certain selects. This is handy for things like `data-subtext`, because Angular doesn't support custom option templates using ngRepeat (although that is another thing I would like to implement into ng-bootstrap-select at some point).

I haven't tackled any performance improvements yet, but I imagine there's some way to reduce the number of times `refresh()` is called.
