### ISSUE TITLE
data-mobile=true bug

### ISSUE THREAD

**Issue by cklown** [silviomoreto/bootstrap-select#1098]
I noticed while using data-mobile="true" with data-live-search="true" in Google Chrome (version 43) Windows 7 (on laptop), clicking on the select menu does nothing, however, tabbing onto the select works well.

Think this was the problem combo in this environment.

Here is the select html tag I used that had the issues:

<select id="test" name="test" class="selectpicker" data-mobile="true" multiple="multiple" data-live-search="true" data-width="100%" data-max-options="5" data-selected-text-format="count>1">

Hope this helps!

**Comment by szegheo** [comment]
+1 and the same bug fog multiple selects like:

```html
<select name="langs[]" class="form-control" multiple data-selected-text-format="count>2">
    <option value="english"></option>
    <option value="dutch"></option>
    <option value="russian"></option>
</select>
```

**Comment by jkrehm** [comment]
I just ran into this same issue with the `multiple` attribute. Here's a fiddle showing the issue: https://jsfiddle.net/jkrehm/88fm70oe/2/.

Because I know the core developers are busy and likely aren't affected by this issue themselves, I'm going to spend a bit of time trying to figure out what's going wrong. Hopefully I'll be able to figure something out.

**Comment by jkrehm** [comment]
Well nevermind, via desktop browsers it makes sense this doesn't work (multiple selects are formatted vastly differently than standard selects) and the issue I was facing on mobile is a [bug with iOS](http://stackoverflow.com/questions/34660500/mobile-safari-multi-select-bug), so not something that can be solved with this library.
