### ISSUE TITLE
'active' class is only applied when liveSearch is on

### ISSUE THREAD

**Issue by andrews05** [silviomoreto/bootstrap-select#1110]
On a non-multiple select, the selected li in the dropdown menu is given the class 'active' (which highlights it blue) if and only if liveSearch is on. Not sure if this is a bug or intentional but I would think the 'active' class should be applied regardless of search.

**Comment by caseyjhol** [comment]
This is intentional. When a select doesn't have liveSearch enabled, the selected option is focused. When liveSearch is enabled, the `active` class must be used, as the focus needs to remain on the input. So, you could modify your `.dropdown-menu>li>a:focus` styling to match that of `.active`.

When bootstrap-select was first released, the liveSearch option didn't exist, so this is a remnant to keep "normal" selects (without liveSearch enabled) consistent with older versions of bootstrap-select. However, at this point, it would probably make more sense to always apply the `active` class to keep styling consistent. @t0xicCode @silviomoreto thoughts?

**Comment by andrews05** [comment]
Ah yup, I understand what you're saying. I just think it should be consistent either way. In my case I'm activating liveSearch on my selects when they have more than a certain number of options, which means they can change from time to time if the number of options changes. The difference in appearance confused me for a long time until I tracked down what the cause was.

A possibly related issue: When using the liveSearch (i.e. typing in it) there's no longer anything to indicate the currently selected item, even if you delete what you've typed and the whole menu returns (this isn't an issue with multiple selects as the tick mark is persistent). In practice it isn't really a big deal but just thought I'd mention it.

**Comment by silviomoreto** [comment]
I agree with you @caseyjhol! We should keep the coherency in both cases. 

Although, I think that we should keep the focus on the input of liveSearch when the dropdown is open. If we just change the `.active` calss place it will lose the focus for the selected option in the dropdown.

**Comment by t0xicCode** [comment]
Same. We've had liveSearch for a while now, so I think we should be fine to replace the old behaviour with a consistent one.

**Comment by Gatunox** [comment]
Same issue here

**Comment by caseyjhol** [comment]
Available in v1.13.0-alpha.

**Comment by y1n0** [comment]
I am getting .active on bs-select element on initialization, even if it was not touched. is this expected?
