### ISSUE TITLE
Placeholder color

### ISSUE THREAD

**Issue by RALGIE** [silviomoreto/bootstrap-select#1139]
Hello,

When I set the title from the select and add an empty element the combobox displays the placeholder(tittle). This is desirable. But the color from the placeholder is not the wright color. It should be the color that is defined in bootstrap/css file. 
Is there a solution to this problem or is this a bug?

**Comment by brunocascio** [comment]
+1

**Comment by myplacedk** [comment]
I don't see a way to do that without modifying bootstrap.

But by adding a class to the button, users can choose to style bootstrap-select the same way they style other form elements.

**Comment by szegheo** [comment]
+1 with some addition:

If an option is already selected (select has value), but then the user later selects an option with no value (tipically the first, blank option), than the select should be showing again the placeholder text with it's custom placeholder color (instead of showing empty text like it does now).
```smarty
<select class="selectpicker" title="Choose a city">
  <option></option> {* show the placeholder title when this is selected *}
  <option value="1">Budapest</option>
  <option value="2">London</option>
  <option value="3">Paris</option>
</select>
```

**Comment by bqst** [comment]
+1

**Comment by msct** [comment]
In the past I've got this feature with a one-liner in the render function.
 
`//Toggle the placeholder class, depending whether we have a valid title yet`
`this.$button.toggleClass('placeholder', (title === ''));`

It was placed right above `if (!title) {`

Default Bootstrap placeholder is color is `#999`, so CSS would be something like:
`.bootstrap-select .btn-default.placeholder {color:#999}`
`.bootstrap-select .btn-default:hover.placeholder,`
`.bootstrap-select .btn-default:active.placeholder {color:#777}`

No Pull request because it has a small bug on initial page load when one uses the `title` attribute on the parent <select> element. I don't use title, I've always use `data-none-selected-text`

**Comment by msct** [comment]
I love it! @caseyjhol
