### ISSUE TITLE
Selectpicker.js Conflicts with Bootstrap Data tables library

### ISSUE THREAD

**Issue by Sahilgoyal190** [silviomoreto/bootstrap-select#1145]
Selectpicker.js Conflicts with Bootstrap Data tables library

**Comment by mouse0270** [comment]
+1

This really sucks, I just found this out.

I love the easy and look of this plugin however my page relies more on Datatables then this plugin. So sadly until this is resolved I have to switch to using other dropdown option. 

It really does suck, because I haven't found a plugin that works as great as this one.

**Comment by Sam-Butler** [comment]
+1

Back to the drawing board!

**Comment by caseyjhol** [comment]
_How_ does it conflict? Might be an easy fix. See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

## Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a [reduced test
   case](http://css-tricks.com/6263-reduced-test-cases/).

5. **Include a live example.** Use [this Plunker debugging template](http://silviomoreto.github.io/bootstrap-select/playground/) to share your isolated test cases. You can also make use of [jsFiddle](http://jsfiddle.net/) or [jsBin](http://jsbin.com/).

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
>
> A summary of the issue and the browser/OS environment in which it occurs. If
> suitable, include the steps required to reproduce the bug.
>
> 1. This is the first step
> 2. This is the second step
> 3. Further steps, etc.
>
> `<url>` - a link to the reduced test case
>
> Any other information you want to share that is relevant to the issue being
> reported. This might include the lines of code that you have identified as
> causing the bug, and potential solutions (and your opinions on their
> merits).

**Comment by Sam-Butler** [comment]
Thanks Casey, you're right, I fell in line with the commenters above instead of submitting a bug report. I'll see what I can do in the next 24 hours; if it can be fixed easily then I would like to use this library in a project this week, but I'm under pressure. Keep this issue open and I'll do my best with a test case in the morning.

**Comment by coogle** [comment]
+1 I also just ran into this. I'll see if I can figure out why exactly, but putting a breakpoint in the initial click of the select box here:

```
      this.$button.click(function () {
        return !that.isDisabled();
      });
```

by stepping into that _without_ DataTables loaded you end up somewhere inside of jQuery and everything works fine. However _with_ DataTables loaded you end up actually inside of DataTables which makes no sense to me.

DataTables must be doing something to hijack the event that is causing problems for the plugin. Sorry I don't know more offhand but that's what I'm seeing.

**Comment by coogle** [comment]
Just a little more color...

With DataTables enabled, if you step through the entire code path with the click event you will note that it actually does render the select box. However, shortly thereafter the select box is destroyed before later in the code. 

The offending code in DataTables is a function `clearMenus`, which gets called during the click event:

```
function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
    $(toggle).each(function () {
      var $this         = $(this)
      var $parent       = getParent($this)
      var relatedTarget = { relatedTarget: this }

      if (!$parent.hasClass('open')) return

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger('hidden.bs.dropdown', relatedTarget)
    })
  }
```

**Comment by coogle** [comment]
I think I found the culprit!

The issue seems to be that, depending on how you are including DataTables, its possible you are including some Bootstrap code twice and causing two events to be bound to the same element that end up cancelling each other out.

Specifically, my version of DataTables had the Bootstrap Dropdown.js code in it, and it was firing after the bootstrap-select event and cleared the menu as soon as it was drawn.

The answer that worked for me was to NOT include the Bootstrap styling library when building your DataTables package.

**Comment by Sam-Butler** [comment]
Aha! That might be it, I actually changed the sequence of includes and
ended up including dropdown.js (separate from bootstrap.js) after
everything else as I just didn't have time (non-paying project) to look
into it, but what you say makes sense.

The symptom I had was the click alone would not reveal the menu, but typing
a key after the click, would.
