### ISSUE TITLE
Navigation links to custom select?

### ISSUE THREAD

**Issue by nuke123** [silviomoreto/bootstrap-select#1146]
I need to use a list of links instead of select with onchange mainly because of seo. I'd like it to read the  links href for the value and redirect on change.

Is there a way to customise this plugin to do this or would it be a needed as a new feature?

**Comment by caseyjhol** [comment]
Just set the value of the select options to the desired URL. Then, just do something like:

```js
$('.selectpicker').on('change', function () {
    window.location.href = $(this).val();
});
```

**Comment by emovere** [comment]
Doesn't fit the need of @howdu 100%, because like him I want an <a href=""> tag for seo optimisation reasons. But it gets at least the work done. Thank you!

**Comment by mikeploeger** [comment]
**@caseyjhol your solution doesnt work for `multiple="multiple"` selects :(**

If its a multi select, it will return an array (instead of a single string) with the `value=""` fields of every selected element.

In my case, the user can filter via Bootstrap-Select.
The new url is inside `<option value="newURL">`.
How can we access the "value" attribute ONLY on the element the user clicked on (not on all elements)? Is there a option for that?

If not, is it possible to set a href="" on the created <a tags, like @howdu initially asked for?

**If you need a demo or more information let me know, I'll be happy to assist you!**

**Comment by mikeploeger** [comment]
**Solution** (for anyone with the same problem (Redirect on multi-select)):
```
$('.selectpicker').on('changed.bs.select', function (e, clickedIndex, newValue, oldValue) {
     location.href = $(this).find('option:eq('+clickedIndex+')').val();
});
```

But it would be AWESOME if we could have a SEO optimized version (with <a href="link" tag)!
@caseyjhol
