### ISSUE TITLE
selectpicker('destroy') does not work properly

### ISSUE THREAD

**Issue by typoworx-de** [silviomoreto/bootstrap-select#1149]
I would expect, that the method of `selectpicker('destroy')` will destroy the bootstrap-select and restore the original select.

This does not work! The original select is left hidden and unfunctional.

**Comment by Messing** [comment]
Did you forget to add the bootstrap-select.css file?

**Comment by typoworx-de** [comment]
No. But may be there is something else confusing the selectpicker?!

So it should be usual that the original select is recovered on calling the destroy-action, right?

**Comment by caseyjhol** [comment]
This is an issue with the way `destroy()` is implemented. See #968. I want to fix it so that the original select element remains, but I also want to provide backwards compatibility. I'm thinking it will be best to change the way that function works and break backwards compatibility, as it's not what most people would expect it to do. I'm trying to imagine a scenario where this would be desired behavior.

Looking at the code, calling `destroy()` simply calls `remove()` - there is no actual destroy function, so users can fall back on `remove()`. This is a no brainer fix - I'll include it in the next version.

**Comment by jacobbroberg** [comment]
I think this relates to the issue I created a while ago: #1143
My issue is not so much that the original select is left hidden, but that the bootstrap select div is left visible
