### ISSUE TITLE
Options from select showing as list <ul><li> on page with CSS turned off(Accessibility)

### ISSUE THREAD

**Issue by gopster** [silviomoreto/bootstrap-select#1209]
As part of accessibility compliance, we have to test the functionality with CSS turned off. When we turn off CSS, the dropdown functionality is there and works as expected, but all the options in <select> also show up as a list <ul> on the page. If you open and close the dropdown once, then the <ul> markup goes away from the page and everything is good. 

Is there a way to turn off the <ul> markup from showing on the page on initial load?

Here is a sample: 

http://jsfiddle.net/gopster/58n1ruox/

1. load the page
2. turn off styles on the page
3. You can see in the result window the <ul> markup
4. Turn the styles back on
5. open and close the dropdown
6. turn off styles on the page
7. Now you don't see the list <ul> markup

**Comment by caseyjhol** [comment]
It's because you've got `data-container="body"` set. By default, regardless of the settings, the menu HTML is generated on page load. Once you open the menu, it is then removed from the default bootstrap-select container and appended to the new container ("body" in this case). I might play around with it and see if the performance increase is worth it to only generate the menu HTML upon clicking on the button.
