### ISSUE TITLE
Programmatically set focus on select

### ISSUE THREAD

**Issue by alvaropag** [silviomoreto/bootstrap-select#1212]
Hello,

How do I set the focus via JS on the bootstrap-select? I tried the focus() function on the select tag, and in the button tag of the generated code (I also tried the div, ul and li, hehehe) but without success. Does anyone know how to set focus on a bootstrap-select?
Thanks

**Comment by Jogai** [comment]
I'm currently doing it like this. The focus moves to the select element insde the dropdown...

```javascript
$("input").selectpicker().parent().find(".selected a").focus();
```

**Comment by Rhend** [comment]
Doesn't work for me :/ I can't find how to put the focus too.. That's really odd

**Comment by caseyjhol** [comment]
Use:

```js
$('#select').data('selectpicker').$button.focus();
```

**Comment by Rhend** [comment]
addEmploye.js:17 Uncaught TypeError: Cannot read property '$button' of undefined.

This is what i got with your code :/

**Comment by Rhend** [comment]
Thanks ! Works like a charm !

**Comment by Jogai** [comment]
Much better, thanks!
Now I'll do it in one step. Example for autocomplete:

```js
$("select.autocomplete").selectpicker().data("selectpicker").$searchbox.focus();
```

**Comment by gititmsc** [comment]
None of the above worked in my case. It focus when selected for the first time after that it's not working

**Comment by axunonb** [comment]
We were using
```
$(document).ready(function() {
    $('button[data-id=ENTER_ID_OF_THE_SELECT_ELEMENT]').focus();
});
```
which seems to be an unambiguous way, because the ID of the select element is used, which contains the ```selectpicker``` CSS class.

**Comment by caseyjhol** [comment]
Focusing on the select element now focuses the button. So you can just do `$('#select-id').focus()`.

**Comment by axunonb** [comment]
> 
> 
> Focusing on the select element now focuses the button. So you can just do `$('#select-id').focus()`.

@caseyjhol Hm, didn't work for me with v1.13.17, while ```$('button[data-id=ENTER_ID_OF_THE_SELECT_ELEMENT]').focus();``` still does.

**Comment by caseyjhol** [comment]
@axunonb Could you link me to an example of it not working?

**Comment by axunonb** [comment]
@caseyjhol Yes, here is the [JsFiddle](https://jsfiddle.net/axuno/34bz01xy/6/) for it.
Strange enough, on Firefox there is no focus, while on Chrome it does focus, but displays the 'original' select:
![picker-focus-on-chrome](https://user-images.githubusercontent.com/10255664/82050257-1cd39a80-96b8-11ea-9fba-5567ee5db8cd.jpg)
You see the 2 alternatives for focusing at the very bottom of the demo code. My working solution is uncommented.

**Comment by caseyjhol** [comment]
@axunonb I'm not able to recreate the issue where the native select element is displayed, but I am able to recreate the focus issue. It looks like it's not working because of jQuery - changing the jQuery version to 3.3.1 in your example, instead of 3.5.1 fixes it (https://jsfiddle.net/caseyjhol/xvurwn1t/3/). It appears the change was introduced in jQuery 3.4.0.

You'll want to follow this issue: jquery/jquery#4382.

A workaround in the meantime is to use the native focus event:

```js
$('#select-id')[0].focus()
```

**Comment by axunonb** [comment]
> changing the jQuery version to 3.3.1 in your example, instead of 3.5.1 fixes it

Looks like jQuery's 3.5.x versions introduced a couple of issues, like [this one](https://github.com/twbs/bootstrap/issues/30553#issuecomment-612617589) with Bootstrap. Unfortunately using jQuery < 3.5 does not seem to be a good idea because of its [vulnerabilities](https://snyk.io/vuln/npm:jquery@3.4.1).

Thanks a lot, also for the workaround!
