### ISSUE TITLE
data-max-options-text takes only the 1st caracter

### ISSUE THREAD

**Issue by vnorguet** [silviomoreto/bootstrap-select#1300]
I have trouble with data-max-options-text option: Only the 1st character of this field is rendered when limitting the number of elements in a list:

```html
<select class="selectpicker form-control"  id="categories" name="categories"  multiple data-none-Selected-Text="Catégorie" data-max-options="2" data-max-options-text="Only two categories are allowed" mobile="true" required>
    <options id="1">foo</>
    <options id="2">bar</>
    <options id="3">bar</>
</selected>```

When selecting the 3rd item, the error is well displayed, but only showing the "O" is displayed in this example.

Platform info:
* Node 5.1.1
* boostrap-select 1.9.4

**Comment by caseyjhol** [comment]
It's because it's looking for an array, not a string, as it needs custom text for both the normal maxOptions and the group maxOptions.

Not an ideal solution, but this should work for you:

`data-max-options-text="[&quot;Only two categories are allowed&quot;, &quot;Only two categories are allowed&quot;]"`

**Comment by vnorguet** [comment]
Ok, I understand why it couldn't work.
Your trick solved my issue!

Thank you!

**Comment by caseyjhol** [comment]
FYI, this would also work:

```html
data-max-options-text='["Only two categories are allowed", "Only two categories are allowed"]'
```

**Comment by lovewuyong** [comment]
Thank you, I see .
