### ISSUE TITLE
Can I apply custom style on dropdown-menu?

### ISSUE THREAD

**Issue by didip** [silviomoreto/bootstrap-select#1302]
I have a custom bootstrap theme and I'd like to modify the `.dropdown-menu` to still be black on white background.

`data-style` attribute seems to only impact the button itself.

**Comment by ouroborus** [comment]
Afaik, `.dropdown-menu` is a standard Bootstrap dropdown menu with some additional styling overlayed by Bootstap Select. So restyle it in your CSS. Keep in mind that Bootstrap Select uses `.dropdown-menu` for both the menu and an inner menu wrapper. Styling against `.dropdown-menu.open` and `.dropdown-menu.inner` seperately may be necessary.

**Comment by hilyin** [comment]
I am having a similar issue. I need to apply custom styling to the dropdown menu, but I am needing to use data-container='body' because of container size / z-index issue. So, being that the menu is only just inside body, that means I can't just use a css selector that specifies just that particular dropdown menu element.

I am thinking maybe allowing the user to specify a class to add to the dropdown menu would resolve this issue. This way I can just apply my styling to that class selector.

Example:

They'd specify a data attribute, such as data-dropdown-class='custom-added-class-name'

Then the HTML in the DOM would be:

```
<body>
<div class="bs-container btn-group bootstrap-select open custom-added-class-name"
     style="top: 58px; left: 240px; width: 130px;">
    <div class="dropdown-menu open" style="max-height: 532px; overflow: hidden;">
        <ul class="dropdown-menu inner" role="menu" style="max-height: 520px; overflow-y: auto;">
            <li data-original-index="0"><a tabindex="0" class="" style="" data-tokens="null"><span class="text">Some Text</span><span
                class="glyphicon glyphicon-ok check-mark"></span></a></li>
            <li data-original-index="1" class="selected"><a tabindex="0" class="" style="" data-tokens="null"><span
                class="text">Some Text</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li>
        </ul>
    </div>
</div>
</body>
```

**Comment by technbuzz** [comment]
Well we can always use JavaScript to access the `.dropdown-menu.open` and add our custom class. 
```
jQuery('.panel__controls')
  .find('.dropdown-menu.open')
  .addClass('panel__ddown');
```
I went specific by adding `.open` to the selector. That's because bootstrap by default doesn't add `.open` to the inner container but to the outer container. This is the behaviour of **bootstrap-select**.

**Comment by hilyin** [comment]
Thank you @technbuzz. I ended up using the template object field when initing the selectpicker with a custom class. Worked great. Thank you for taking your time to reply.
