### ISSUE TITLE
meteor package refresh to 1.10.0 please

### ISSUE THREAD

**Issue by morgunder** [silviomoreto/bootstrap-select#1314]
i see a couple of packages on atmospherejs.com that wrap this package.  the one which appears the most recent: https://atmospherejs.com/jesperwe/bootstrap-select seems to be wrapping version 1.7.4.

i'm asking because i'm trying to use this in a meteor project on a form with several select boxes.  when i enable mobile: true, the multiple selects work ONLY on the mobile phone and no longer work in Chrome.  and i'm hopeful that this has been addressed since september 30th.

**Comment by caseyjhol** [comment]
That's how `mobile: true` works. That's why you need to check on your end if the device is a mobile device, and only set `mobile: true` if that's the case. See http://silviomoreto.github.io/bootstrap-select/methods/#selectpickermobile. When that option is set, the native select element is used when you click on the button. Since multiple selects don't have dropdown menus on computers, the effect only works on mobile devices.
