### ISSUE TITLE
Turn off multiple select for a particular option

### ISSUE THREAD

**Issue by GNSubrahmanyam** [silviomoreto/bootstrap-select#1585]
### Turn off multiple select for a particular option.

```
<select class="selectpicker" id="type" multiple>
          <option value="Type 1">Type 1</option>
          <option value="Type 2">Type 2</option>
          <option value="Type 3">Type 3</option>
          <option value="Type 4">Type 4</option>
          <option value="Type 5">Type 5</option>
</select>
```

If Type 3 is selected then Remove Multiple Attribute from .selectpicker else Add Multiple Attribute.

Type 3 can't clumped with  Type 1, Type 2, Type 4, Type 5. Only Type 1, Type 2, Type 4, Type 5 can be clumped. 

Is there any option to do this in Bootstrap-select.

Thanks in Advance.

**Comment by hwangm** [comment]
One way I can think of doing this is through scripting. Check the value of the selectpicker after user changes selection (changed.bs.select event) and if Type 3 is selected, unselect the rest of the options. I had a problem with this as well, trying to use the multiple select with an "Any" category that should clear if anything else was selected. What I ended up doing is setting the title to "Any" so that when nothing was selected, it would show Any. And that would disappear when the user chose one of the categories.

**Comment by jkabat** [comment]
You could also set maxOptions to 1 on change event when Type 3 is selected (after clearing the rest of the options) to ensure the number of posted options is OK. Did not try it myself thought - it may require more work and may not be worth it.

http://silviomoreto.github.io/bootstrap-select/options/

**Comment by caseyjhol** [comment]
@jkabat's solution is probably the best route. Implementing the option by default is probably outside the scope.
