### ISSUE TITLE
Not working in Aurelia

### ISSUE THREAD

**Issue by devingoble** [silviomoreto/bootstrap-select#1661]
I'm using the latest version of bootstrap-select (1.12.2), bootstrap (3.3.7), and jQuery (3.1.1). It ends up generating the following:
![image](https://cloud.githubusercontent.com/assets/2547980/23471593/bd716698-fe5e-11e6-9864-f87e5acc267f.png)

Here is what I'm doing to set it up in a simple app:
```
  <select>
    <option>foo</option>
    <option>bar</option>
    <option>baz</option>
  </select>
```
```
attached() {
    $("select").selectpicker();
  }
```

It seems to work outside of Aurelia ok. I'm wondering if the two are fighting somehow?

**Comment by caseyjhol** [comment]
It looks like the CSS isn't being loaded properly.

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

## Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a [reduced test
   case](http://css-tricks.com/6263-reduced-test-cases/).

5. **Include a live example.** Use [this Plunker debugging template](http://silviomoreto.github.io/bootstrap-select/playground/) to share your isolated test cases. You can also make use of [jsFiddle](http://jsfiddle.net/) or [jsBin](http://jsbin.com/).

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
>
> A summary of the issue and the browser/OS environment in which it occurs. If
> suitable, include the steps required to reproduce the bug.
>
> 1. This is the first step
> 2. This is the second step
> 3. Further steps, etc.
>
> `<url>` - a link to the reduced test case
>
> Any other information you want to share that is relevant to the issue being
> reported. This might include the lines of code that you have identified as
> causing the bug, and potential solutions (and your opinions on their
> merits).

**Comment by KarstenHoehne** [comment]
In order to use external libs with aurelia, be sure to add them to the aurelia.json.
See http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/10 for details.

I had some success with adding to aurelia.json:
```
"dependencies": [ ... ,
{
			    "name": "bootstrap-select",
			    "path": "../node_modules/bootstrap-select/dist",
			    "main": "js/bootstrap-select.min",
			    "resources": [
			      "css/bootstrap-select.min.css"
			    ]
			  },
...
```


in app.html:
```
<template>
...
<require from="bootstrap-select/css/bootstrap-select.min.css"></require>
...
```

and in your js file that contains the attached() method:
```
...
import {selectpicker} from 'bootstrap-select';
...
attached(){
		$('.selectpicker').selectpicker();
	}
...
```

NOTE: It doesn't seem to work once you use 
`<option repeat.for="obj of objects" value.bind="onj.id">${obj.name}</option>`

probably because using repeat.for only really creates the option tags at runtime, i am guessing bootstrap-select needs to run through the DOM <option>'s which doesn't work when aurelia only generates them at runtime. But thats only a guess on my part.
