### ISSUE TITLE
liveSearch not working

### ISSUE THREAD

**Issue by dfostic** [silviomoreto/bootstrap-select#1717]
Feature not working as supposed, like selectpicker with data-live-search, selectpicker with multiple.etc.
but selectpicker show-tick form-control works fine.

Versions used:
Project: Angular2 with Typescript
OS: Windows 10
"bootstrap": "~3.3.7",
"bootstrap-select": "^1.12.2"
Jquery version: 3.1.1
browsers: chrome, firefox, IE

Actually it works exactly like test.html in  bootstrap-select-1.12.2/docs/docs/playground/test.thml.

If you download  v1.12.2 from https://silviomoreto.github.io/bootstrap-select/ and check /docs/test.html it works fine, exactly as supposed, if you try /docs/docs/playground/test.thml it is working with errors, like no searchPanel for data-live-search="true", etc. Please see picture attached of palyground/test.html

![bootsrap-select](https://cloud.githubusercontent.com/assets/13340030/26080696/bc036be0-3995-11e7-9a4a-ff0e9183dcad.png)

If I use <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css"> then i have select hidden
I will be glad to provide more details if you cannot reproduce it in playground.

**Comment by caseyjhol** [comment]
Can you try updating to the newest version of bootstrap-select to see if the issue persists? I'm unable to recreate this on my end using v1.12.2.

**Comment by dfostic** [comment]
Newest version is doing exactly the same. You can download newest version from https://silviomoreto.github.io/bootstrap-select/, unzip it and try /docs/docs/playground/test.thml. This is how it works on my side

**Comment by caseyjhol** [comment]
/docs/docs/playground/test.html is simply used for the layout to generate the Plunkr playground (http://silviomoreto.github.io/bootstrap-select/playground/). To test locally, you want to use test.html in the root directory.

**Comment by dfostic** [comment]
My issue is when i use bootstrap-select in my app, it behaves exactly the same as docs/docs/playground/test.html
and not behaving like /docs/docs/playground/test.thml

**Comment by caseyjhol** [comment]
Based on the screenshot you've provided, it seems likely that some file is not loading properly - either jQuery, bootstrap.js, bootstrap.css, bootstrap-select.js, or bootstrap-select.css.

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

## Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a [reduced test
   case](http://css-tricks.com/6263-reduced-test-cases/).

5. **Include a live example.** Use [this Plunker debugging template](http://silviomoreto.github.io/bootstrap-select/playground/) to share your isolated test cases. You can also make use of [jsFiddle](http://jsfiddle.net/) or [jsBin](http://jsbin.com/).

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
>
> A summary of the issue and the browser/OS environment in which it occurs. If
> suitable, include the steps required to reproduce the bug.
>
> 1. This is the first step
> 2. This is the second step
> 3. Further steps, etc.
>
> `<url>` - a link to the reduced test case
>
> Any other information you want to share that is relevant to the issue being
> reported. This might include the lines of code that you have identified as
> causing the bug, and potential solutions (and your opinions on their
> merits).

**Comment by tomczek** [comment]
I had a similar problem. My search-result for liveSearchStyle "startsWith" was always empty for each search-value. After a while I've figured out, that this was an mapping issue. This is how it worked for me in Aurelia:

```
<abp-select
	picker-options.bind="{ liveSearch: true, dropupAuto: false, noneSelectedText: '', liveSearchStyle: 'startsWith' }"
	collection.bind="items"
	selected-item.bind="selectedItem"
	data-mapping-structure.bind="{ option: 'standardDisplayText', content: 'standardDisplayText' }"
	object-key="key">
</abp-select>

export interface IItem {
    key: string;
    value: string;
    displayText: string;
}

public items: IItem[];
public selectedItem: IItem;

items = [
	{ key: '121', value: 'hello', displayText: '121 - hello' },
	{ key: '112', value: 'world', displayText: '112 - world' },
];

search for: "12"
result: "121 - hello"
```
