### ISSUE TITLE
Bootstrap Webpack Issues

### ISSUE THREAD

**Issue by DDDgfx** [silviomoreto/bootstrap-select#1820]
Hi - Im looking forward to using this plugin but I am loading it with ES6 modules and using webpack and while bootstrap-select is clearly impacting the page, the styles are off and options are appearing in a second box to the right of the dropdown. Could this be because I am loading bootstrap js components individually?

<img width="553" alt="screenshot 2017-09-29 12 11 54" src="https://user-images.githubusercontent.com/1700366/31025178-8d55666e-a50f-11e7-8463-24ac57706514.png">

**Comment by grounded-warrior** [comment]
I am experiencing this as well using webpack

**Comment by matthiasballreich** [comment]
you have to include the bootstrap-select css.
But then i got another problem. I can not select any options, because none are shown.

I included bootstrap-select with webpack. there in my app.js i included the js via "import("bootstrap-select") and in my scss i imported the sass of bootstrap-select. But why i don't see my options if i click into the select-box? I got only an empty list.

**Comment by caseyjhol** [comment]
@matthiasballreich What version of Bootstrap are you using?

**Comment by DDDgfx** [comment]
Im using 4. I would still love to use this library. Nothing else out there is quality to solve this problem.

**Comment by caseyjhol** [comment]
Bootstrap 4 is not yet supported, but it will be available in an upcoming release. Please follow #1135 for updates.
