### ISSUE TITLE
Not working anymore when upgraded to bootstrap 4 !!!

### ISSUE THREAD

**Issue by benjircse** [silviomoreto/bootstrap-select#1904]
When I upgraded to Bootstrap 4 select elements are not showing anymore. Is the bootstrap-select supported with bootstrap 4.0?

**Comment by carnevalli** [comment]
Same issue here. I've tried update the demo files with BS4 and it not worked either.

**Comment by chrisw73** [comment]
Same issue. Now, that BS4 is final, im am desperately wayting for new releases of BS extensions like bootstrap-select...

**Comment by cocowalla** [comment]
@benjircse  @carnevalli @chrisw73 you need to use the search function before opening a new issue - see #1135 for more info.

@benjircse, you should probably close this issue to avoid cluttering the issues list with yet another 'Bootstrap 4' issue, since #1135 is the active issue for Bootstrap 4 support.

**Comment by ionesculiviucristian** [comment]
Somebody likes that thumb down emoji...

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by mickelsonmichael** [comment]
@caseyjhol potentially consider adding a version selector or notification to your [older site](http://silviomoreto.github.io/bootstrap-select/). I was struggling with this issue because that site came first in my Google searches
