### ISSUE TITLE
How to use it with jquery validate

### ISSUE THREAD

**Issue by vbrigand** [silviomoreto/bootstrap-select#215]
Hello,

How to use it with jquery validate?
http://jqueryvalidation.org/
Thanks.

**Comment by ramesht6** [comment]
I have same issue @dubhe85 faced, but i don't know  how to add handler for .selectpicker
please can help me @t0xicCode / @dubhe85, could you paste code here.

**Comment by Ejilarasan** [comment]
@arathael am getting the error message by ignore method. In order to hide the error message on select change event as said by @dubhe85 and also its get cleared. Then once again am clicking the button error message displayed even the select value is not equal to null. Please comment the correct method for showing and hiding the error message as per the select option input.

**Comment by quetzaluz** [comment]
@Ejilarasan You may have found a similar solution but this comment from a different issue offers good advice on how to toggle the error message upon change:
https://github.com/silviomoreto/bootstrap-select/issues/1223#issuecomment-163349027
