### ISSUE TITLE
size and data-size not always working

### ISSUE THREAD

**Issue by dfliess** [silviomoreto/bootstrap-select#31]
I Think that the size option stopped working for element's that have not been attached to the DOM.

For what I've seen without knowing the full code the issue could be in line 31

var liHeight = parseInt(menuA.css('line-height')) + menuA.outerHeight(); //NaN

.css('line-height') is "".

At least on Chrome v23.0.1271.101:

$('<a href=""></a>').css('line-height')  

I've patched by the moment with a default value like this:

var liHeight = parseInt(menuA.css('line-height'),10)||25 + menuA.outerHeight();

I know it's not the perfect solution....but not sure how to fix it.

**Comment by MikeMazz23** [comment]
So there are 2 common practices to make bootstrap type dropdowns. First is to use a select and the second is to a ul and li options (data toggle and dropdown-menu). When you use the select version, the first time the dropdown is expanded a ul is created with all li options having the values from the select options tags. There are now 2 lists in your page DOM. The ul li list and the original select. When you continue to play with the dropdown you will see the li class gets "selected" added to the option you picked, however the original select remains unchanged. The chrome dev tools shows this nicely by highlighting what has changed. This is probably why the size doesn't take effect immediately, bc it has to create the ul li list first. Why not does init? who knows..
This is unfortunate bc now we cannot use this great plugin with selects, only ul lists.
I know this issue was closed a long time ago, but maybe this will shed some light on the issue and help someone find a solution.
