### ISSUE TITLE
Support for removing <options> from <select> element

### ISSUE THREAD

**Issue by kayzee** [silviomoreto/bootstrap-select#52]
When I remove an option element from a select, the bootstrap-select doesn't update.  I tried removing the full $('.bootstrap-select') group and re-initializing by calling .selectpicker(), but it won't update and recreate the dropdown.

```
$("#select_list option[value='New Test List']").remove();
```

Any suggestions?

Thanks!

**Comment by Eagle3386** [comment]
Hey everyone,

I'm working with the awesome Bootstrap Select, but experienced a weird behavior which you might be able to help me with. It's within a Bootstrap modal dialog where the first paragraph holds the item selector and whenever that selector is changed, the selected option's detail data (manufacturer, color, etc.) is loaded via AJAX.

The relevant JavaScript code:
```javascript
$(document).ready(function () {
  var deleteItem = $('#delete-item');
  var itemManufacturer = $('#item-manufacturer');
  var itemSelector = $('#item-selector');
  var itemSelectorOption = $('#item-selector option'); // also tried: $('#item-selector option:selected');
  // ... code left out for terse reasons ...    

  deleteItem.click(function () {
    var itemID = itemSelector.val();

    $.ajax({
      // ... code left out for terse reasons ...
    }).done(function (response) {
      if (response > 0) {
        itemSelectorOption.eq(0).remove();
        itemSelector.append('<option class="hidden"></option>');
        itemSelector.selectpicker('refresh');

        itemManufacturer.selectpicker('deselectAll');
        // ... several more lines, resetting other input fields ...
      }
        // ... else left out for terse reasons as well ...
    });
  });
});
```
As you can see, I've tried to incorporate the solution suggested by @caseyjhol in https://github.com/silviomoreto/bootstrap-select/issues/52#issuecomment-13754729, but didn't have any luck after the first removal. Also, since I use the `title` attribute, `.eq(0)` gives me that "placeholder" text, but even `.eq(1).` only removes the option the first time I click the delete button.

Now, the HTML "template":
```html
<select id="item-selector" class="selectpicker show-menu-arrow show-tick" data-id="' . $item["itemID"] . '" data-width="479px" title="Please select an item">
{PHP code which loops the following line for each item}
  <option value="' . $item["ItemID"] . '">' . $item["ItemConcatName"] . '</option>
{PHP code which loops the above line for each item}
</select>
```

So, my problem is: the `deleteItem` button only works the first time it's clicked. Each consecutive click resets the other input fields, but not `itemSelector`.

What am I doing wrong and how can I fix that? Would it be possible to enhance Bootstrap Select in order to offer add/delete methods?

Regards,
 Martin

**Comment by silviomoreto** [comment]
This may happen because of the query for the  `itemSelectorOption` was made outside the scope of the request action. try to move the line `var itemSelectorOption = $('#item-selector option');` before the `itemSelectorOption.eq(0).remove();`, so you will update the selector for the options

**Comment by Eagle3386** [comment]
Well, that makes the delete button working and the `select` menu resetting its text to the `title` attribute's value.
But unfortunately, no entry is removed from the dropdown menu this way.

**Comment by Eagle3386** [comment]
Nevermind, I've fixed it myself. So, in essence, the correct lines (for deleting the currently selected option) read like this:
```javascript
var itemSelectorOption = $('#item-selector option:selected');
itemSelectorOption.remove();
itemSelector.selectpicker('refresh');
```

Thanks for your help, @silviomoreto! :)

**Comment by Eagle3386** [comment]
I have to come back one more: how to raise the changed.bs.select event manually?
Because prior to deleting the currently selected option, I set the next sibling as being select by calling
```javascript
itemSelector.selectpicker('val', $('#item-selector option:selected').next().val());
```

But this doesn't raise the changed event which therefore prevents the itemManufacturerSelector from being changed appropriately (i. e. new item means new manufacturer).

**Comment by caseyjhol** [comment]
```js
itemSelector.trigger('changed.bs.select');

**Comment by Eagle3386** [comment]
Well, I overlooked that "Option" suffix and for about 2 hours, I've triggered itemSelectorOption instead of itemSelector. I'm so sorry, @caseyjhol. I want to curl up and die. -.-

**Comment by silviomoreto** [comment]
@Eagle3386 do not worry! the important thing is that you solved your problem! hope bootstrap-select helped you in your project

**Comment by Eagle3386** [comment]
It does tremendously! :)

However, as an improvement, I'd like to suggest a better approach for the default text by implementing support for a placeholder value - much like native HTML5 `input` elements already offer.

Currently, the `title` attribute is somewhat used for that. But this gave me many headaches, because I'm in a scenario where I do need both, as placeholder (e. g. when a selected option is removed or simply deselected) and at the same time as the default value (e. g. when the page gets loaded or the modal dialog received the content after being rendered by PHP and transfered via AJAX).

As a feature request, I'd like to ask for native AJAX support of the data source, as, to put it simple, [Ajax-Bootstrap-Select](https://github.com/truckingsim/Ajax-Bootstrap-Select) sucks. Right now, I have to use this code to achieve AJAX loading:
```javascript
itemManufacturer.selectpicker()
  .on('loaded.bs.select', function (event, clickedIndex, newValue, oldValue) {
    $.getJSON('/path/to/item-manufacturers.php', function (response) {
      itemManufacturer.html('');
      $.each(response, function (key, value) {
        itemManufacturer.append('<option value="' + value.ID + '">' + value.Name + '</option>');
      });
    }).done(function () {
      itemManufacturer.selectpicker('refresh');
      itemManufacturer.selectpicker('val', itemManufacturer.data('initial-manufacturer'));
    });
  });
```
So, it would be really awesome, to just give the JSON-url as a settings property and also have a placeholder option. :)
