### ISSUE TITLE
How to set own height for select?

### ISSUE THREAD

**Issue by DjSunrise** [silviomoreto/bootstrap-select#524]
How to set own height for select?
I set width according "data-width" . But I didn't find "data-height" option.

**Comment by Jcerwin** [comment]
Bootstrap 3 button styles appear to be broken in 1.6.4. v1.6.3 will properly resize the control height based on a <code>data-style</code>, but v1.6.4 does not. You can recreate the behavior by switching between versions on cdnjs.cloudflare.com.

Example:
<code>data-style="btn btn-default btn-xs" </code>

**Comment by abdo-host** [comment]
I recently spent an hour trying to find how to restrict the height of a dropdown. Turns out the size attribute for select tags is set to 'auto' in the javascript file. For me, it was around line 369.

The solution is simple:

Set `size: '10' `//or however many options you want to be listed

```
$('.selectpicker').selectpicker({
   size: '10'
});
```

width 100%

```
<select class="selectpicker" data-width="100%">
  ...
</select>
```
