### ISSUE TITLE
is it possible to have multi-line options?

### ISSUE THREAD

**Issue by cyberglot** [silviomoreto/bootstrap-select#532]
Hi folks,

I am in a need to build an select with multi-line options like that:

![](https://i.cloudup.com/sVRP2g7owJ.png)

I've looked intro the examples and the issues and I didn't find a way to implement it. Is it possible?

Thanks.

**Comment by beanvonbaron** [comment]
Hi There,  
I looked at that option but I am using an asp:DropdownList control for my project.
I don't know how I can use the data-content attribute when the values/options are created server side.
Any advice?
Here is an example of what I am looking for but again it's not using the dropdown controller.  http://jsfiddle.net/ZTs42/2/

**Comment by EcoFreak** [comment]
I managed to fix this by adding this class `large-bootstrap-select` to the select that in turn is copied to the bs-container class.

`<select class="selectpicker large-bootstrap-select"  ....`

It's important that the `white-space` rule is present because it changes how the li treats whitespace and in turn break the text.

```
.bs-container.large-bootstrap-select {
  .dropdown-menu {
    width: 500px;
    li a span.text {
      word-wrap: break-word;
      white-space: normal;
    }
  }
}
```


**Before**:

![image](https://cloud.githubusercontent.com/assets/3418386/24661012/1764c35c-1949-11e7-94ef-3f8c7884efd4.png)


**After**:

![image](https://cloud.githubusercontent.com/assets/3418386/24660980/f9c9f15a-1948-11e7-9037-4dbd111ee645.png)

Hope it helps

**Comment by rajupatel1000** [comment]
How to select box text show in 2 line?
Not working my css in ( Mozilla Browser )...But support in Chrome ...

MY CSS
select {
white-space: normal;
line-height: normal;
}

![my select box images](https://user-images.githubusercontent.com/43883354/46595651-1aca5280-caf7-11e8-9f23-56f33c0895a0.png)

**Comment by jesusgarza** [comment]
Seems that Multi-line options no longer works.
I tried the same fiddle, changed the file versions and it doesn't work.
http://jsfiddle.net/t0xicCode/454Lqbz8/

**Comment by caseyjhol** [comment]
@jesusgarza Multi-line selects should now be working in v1.13.7.

**Comment by jesusgarza** [comment]
Great Casey, thanks!!

**Comment by ispweb** [comment]
I want to use multi-line with bootstrap-select, but when i select the option it should display the option value

`<select class="selectpicker">`
`    <option data-content="First Line<br>Second Line">Mustard</option>`
`    <option data-content="House Number Street<br>City, State<br>Zip Code">Ketchup</option>`
`    <option data-content="Single line address">Third Address</option>`
`</select>`


So when i select `"First Line<br>Second Line"` the select should display : Mustard

Is this possible, didn't find a solution on internet jet.
