### ISSUE TITLE
z-index too high

### ISSUE THREAD

**Issue by udondan** [silviomoreto/bootstrap-select#608]
Really like this package!

Just found a problem with too high z-index. It conflicts with Bootstrap modals, which _should_ be laying over everything else. Had to give the modal a `z-index` of 2001 to get over the dropdown.

**Comment by gtristan** [comment]
@udondan Curiously, why is it important to you to have a z-index below the bootstrap modal ?

What happens when you actually have a select triggered from a scrollable region inside a modal ?

See issue 875 for an example of the problem the fix for this bug causes.

**Comment by udondan** [comment]
I see how this conflicts when the select is **in** the modal. The problem is, the select would be above the modal, even if it was not inside, without the lower `z-index`.

**Comment by gtristan** [comment]
I'll see if I can work around this by setting the data-container to the modal <div> itself, but I worry that it might cause the modal to grow in the process, the only reason I need data-container to be "body" is because other wise it stays hidden inside a scrollable area inside the modal.

It also seems strange to me that a bootstrap modal can be active at the same time as a select is active, but I suppose there must be some use case demanding that.

**Comment by udondan** [comment]
> It also seems strange to me that a bootstrap modal can be active at the same time as a select is active, but I suppose there must be some use case demanding that.

There might be, but not in my case. The problem was more that the select did not automatically close when the modal was clicked. I had the problem on this project: http://www.localfont.com/ You can partially simulate the original behavior. Click on the left select to open the options, then click on the mail envelop at the bottom. What opens is not a modal, but you see the select does not automatically close the options. I had the exact same with the modal, which you can open with the question mark at the right side of the select fields.
