### ISSUE TITLE
container : "body' leaves a copy of object in body

### ISSUE THREAD

**Issue by mafar** [silviomoreto/bootstrap-select#630]
Hi,
I am using select2 in table in bootstrap. And i am using `container : "body'` option to fix the problem (because my table uses overflow property) but the problem is my app is single page app and for every selectpicker, an object is created at body. 

Even thought my main container is emptied for different actions but I am concerned about a copy of selectpicker created at end of body and it keeps adding as many times as it appears. Is there an intelligent way to remove this copy if main select-picker control is deleted ?

**Comment by tarcon** [comment]
This issue is still present. Each Selectpicker with "container: 'body'" generates a DOM element when opening the dropdown. These elements are not removed on close.

This can be observed in your demo page.

This is a major issue for single page apps, since they can end up with a large number of such DOM fragments.

I would expect the selectpicker to remove the generated DOM elements on close.
