### ISSUE TITLE
readonly atribute

### ISSUE THREAD

**Issue by KaduAmaral** [silviomoreto/bootstrap-select#653]
The attribute readonly need to work like disabled...

**Comment by moorecreative** [comment]
I'd like to comment on this to help it show in search engines... I spent 15 minutes thinking about and searching for information on how to make this multi-select box or dropdown field ReadOnly so that it could display a list within the form, but not have it be changeable by the user.

Now that I see the simple response, I realize it was like searching the internet for "how to turn an escalator into simple stairs"

I looked at other suggestions which suggested changing to add an "onclick="return false;"" action, but that still is a workaround. I think that the best option, if needing a multiselect to be read only is to instead make a hidden form field with the values in place and readonly=true, and then display a bullet list within the form that displays the values. In this way, there is no confusion from the user and is using each element in the way it was intended.
