### ISSUE TITLE
Bug in "SELECTPICKER PLUGIN DEFINITION"

### ISSUE THREAD

**Issue by alexdpunkt** [silviomoreto/bootstrap-select#715]
```
    // SELECTPICKER PLUGIN DEFINITION
    // ==============================
    function Plugin(option, event) {
        // get the args of the outer function..
        var args = arguments;
        // The arguments of the function are explicitly re-defined from the argument list, because the shift causes them
        // to get lost
        //noinspection JSDuplicatedDeclaration
        var option = args[0],
            event = args[1];

// !!! at this point, options is an object - everything OK 

        [].shift.apply(args);

// !!! at this point, options is undefined

        var value;
        var chain = this.each(function () {
```

--> See my "!!!" comments. 

This bug causes the selectpicker plugin to ignore the options on my Samsung GT-S5690 (Android 2.3.6) - might occur on other devices with Android 2.3 too.

Unfortunately I see no JavaScript Error. 

My temporary solution...

```
        // SELECTPICKER PLUGIN DEFINITION
    // ==============================
    function Plugin(option, event) {
        // get the args of the outer function..
        var args = arguments;
        // The arguments of the function are explicitly re-defined from the argument list, because the shift causes them
        // to get lost
        //noinspection JSDuplicatedDeclaration
        var _option = option;

        var option = args[0],
            event = args[1];

        [].shift.apply(args);

        if(typeof option == 'undefined')
            option = _option;

        var value;
        var chain = this.each(function () {
```

**Comment by lazlolazarous** [comment]
This problem also exists on IE9, and the current fix doesn't completely solve the problem.
The shifting of the arguments causes both the local variables to change (_option_ and _event_).
That means the check for (_option_ == 'undefined') only works if _event_ is undefined, as _option_ becomes _event_, and _event_ becomes whatever followed it.
(and there are arguments that follow _event_ in certain cases. IE: _setStyle()_)
It is probably best to not override a parameter with a local variable of the same name, as for some reason the JS interpreter for IE9 alters the local value after the shift.
I refactored the code to use _\_option_ and _\_event_ throughout instead, and that seems to solve the problem:
<pre><code>  function Plugin(option, event) {
    // get the args of the outer function..
    var args = arguments;
    // The arguments of the function are explicitly re-defined from the argument list, because the shift causes them
    // to get lost
    // The conditionals, and use of _option and _event throughout, fix a bug in the js implementation on android 2.3 and IE9 #715
    var _option = args[0] ? args[0] : option,
        _event = args[1] ? args[1] : event;
    [].shift.apply(args);

    var value;
    var chain = this.each(function () {
      var $this = $(this);
      if ($this.is('select')) {
        var data = $this.data('selectpicker'),
            options = typeof _option == 'object' && _option;

        if (!data) {
          var config = $.extend({}, Selectpicker.DEFAULTS, $.fn.selectpicker.defaults || {}, $this.data(), options);
          $this.data('selectpicker', (data = new Selectpicker(this, config, _event)));
        } else if (options) {
          for (var i in options) {
            if (options.hasOwnProperty(i)) {
              data.options[i] = options[i];
            }
          }
        }

        if (typeof _option == 'string') {
          if (data[_option] instanceof Function) {
            value = data[_option].apply(data, args);
          } else {
            value = data.options[_option];
          }
        }
      }
    });
</code></pre>

**Comment by t0xicCode** [comment]
Would you mind making a PR or a patch for this?

**Comment by lazlolazarous** [comment]
---
 js/bootstrap-select.js | 23 ++++++++---------------
 1 file changed, 8 insertions(+), 15 deletions(-)

diff --git a/js/bootstrap-select.js b/js/bootstrap-select.js
index 3d13c72..6264cf8 100644
--- a/js/bootstrap-select.js
+++ b/js/bootstrap-select.js
@@ -1148,28 +1148,21 @@
     // get the args of the outer function..
     var args = arguments;
     // The arguments of the function are explicitly re-defined from the
argument list, because the shift causes them
-    // to get lost
-    //noinspection JSDuplicatedDeclaration
+    // to get lost/corrupted in android 2.3 and IE9 #715 #775
     var _option = option,
-        option = args[0],
-        event = args[1];
+        _event = event;
     [].shift.apply(args);

-    // This fixes a bug in the js implementation on android 2.3 #715
-    if (typeof option == 'undefined') {
-      option = _option;
-    }
-
     var value;
     var chain = this.each(function () {
       var $this = $(this);
       if ($this.is('select')) {
         var data = $this.data('selectpicker'),
-            options = typeof option == 'object' && option;
+            options = typeof _option == 'object' && _option;

         if (!data) {
           var config = $.extend({}, Selectpicker.DEFAULTS,
$.fn.selectpicker.defaults || {}, $this.data(), options);
-          $this.data('selectpicker', (data = new Selectpicker(this,
config, event)));
+          $this.data('selectpicker', (data = new Selectpicker(this,
config, _event)));
         } else if (options) {
           for (var i in options) {
             if (options.hasOwnProperty(i)) {
@@ -1178,11 +1171,11 @@
           }
         }

-        if (typeof option == 'string') {
-          if (data[option] instanceof Function) {
-            value = data[option].apply(data, args);
+        if (typeof _option == 'string') {
+          if (data[_option] instanceof Function) {
+            value = data[_option].apply(data, args);
           } else {
-            value = data.options[option];
+            value = data.options[_option];
           }
         }
       }
--
