### ISSUE TITLE
all items selected when i add options via jquery on IE

### ISSUE THREAD

**Issue by rizerzero** [silviomoreto/bootstrap-select#834]
Hi , i have an issue i think it's a bug , so i fill  a select with jquery and it work but when i fill on select with the data-live-search="true" attribute it will not work on IE , it will select all items by default and it will be impossible to select an item ,
here is a demo of the issue , 

so if you select region2 it will be impossible to select a city on IE  
http://jsfiddle.net/nr54vx7b/17/

Thank you .

**Comment by alexander-ruehle** [comment]
I have the same problem with IE 10 and 11.

**Comment by rbartnik** [comment]
Same. This is preventing us from upgrading from 1.5.4, which we'd like to do to get the fix for empty lists throwing a JS error.

**Comment by steinhoff1989** [comment]
Same for me. Problem occured by adding new Options to an empty sleect, or by adding Options after calling the .refresh() function in Javascript.

Workaround:
1.) Add your Options
2.) .selectpicker('refresh');
3.) .selectpicker('deselectAll');
4.) .selectpicker('refresh');

Updated "rizerzero"'s fiddle:
http://jsfiddle.net/nr54vx7b/63/

**Comment by Shashtri** [comment]
I have also same issue, data-live-search="true" attribute not working in IE, When click on select field, browser getting hang. If we remove data-live-search="true" attribute, Select drop down working fine.

**Comment by caseyjhol** [comment]
What exactly is the issue here? I know there are issues with liveSearch when using liveSearchPlaceholder in IE, but that doesn't appear to be the issue here. Using the example in the original message, things appear to be functioning properly.

**Comment by rbartnik** [comment]
When rebinding the list of options and calling refresh, in IE, the data-original-index attributes on the <li> elements were all being set to 0 instead of properly incrementing, resulting in every item in the list being marked selected and active once refresh was called. You can see a video of this behavior here: http://screencast.com/t/xh2BwBFo6sWN

This behavior was introduced in 1.6.3, which was the current version at the time of the original posting, and appears to have been fixed in 1.6.4.

**Comment by viveknaskar** [comment]
@steinhoff1989 Thanks, man! It worked for me.
