### ISSUE TITLE
loading option content from mysql

### ISSUE THREAD

**Issue by cbakar** [silviomoreto/bootstrap-select#882]
When the content of select box is loaded ajax|js from mysql they don't show but still searchable.

**Comment by gtristan** [comment]
This really works for me.

Are you calling `$(element).selectpicker ('refresh');` every time an option is added, or it's appearance changes ?

**Comment by t0xicCode** [comment]
If you don't cal `refresh`, as @gtristan mentionned, the selectpicker won't update (we cache the selectpicker).

**Comment by cbakar** [comment]
i wasn't but still no showing! -thanks for the help!

**Comment by mferrodriguez** [comment]
Don't know if all you guys solved your issues with this, but still in 2018, this issue was causing me more than one headache.  The solution I found, indeed, was using `refresh` after the ajax call returned the data.  But did it like so:

`$.get('url',{params},function(data){ $(element).html(data); $(element).selectpicker('refresh'); });`

Meaning that yes, `refresh` does solve the problem, but it has to be executed **inmediately** after the DOM element has changed or received the intended data.

Hope it helps !
