### ISSUE TITLE
IE10-11 live refresh bug

### ISSUE THREAD

**Issue by Adns** [silviomoreto/bootstrap-select#885]
In IE10-11, dynamics select doesn't work. if there are 2 selects and second select data depends of the first selected option, the second select is'not selectable after $('select').selectPicker('refresh') call.

Example : http://jsfiddle.net/codeandcloud/nr54vx7b/

**Comment by allanjackson** [comment]
I'm having this same problem, except the select box I'm trying to use is a "multiple" select. Instead of not being able to select anything, no matter which value you click, it selects the first one. The display updates to indicate that all of the items are selected though...

**Comment by allanjackson** [comment]
The problem seems to be something about updating the options in the select box followed by an immediate refresh call.

I added a manual "refresh" button to the above jsfiddle. Any time you use the manual refresh, the second select box will behave as expected. Changing the value of the first select box will re-break the second box.

http://jsfiddle.net/3rxut4bv/

I was also able to get it to work by putting the refresh call in a setTimeout() of ~5 seconds, but this didn't seem to fix it 100% of the time.

**Comment by allanjackson** [comment]
I was able to fix the problem by using the non-minified version of the code. So something in the minification is causing problems.

For some reason I wasn't able to get the jsfiddle example to work even with non-minified code. Maybe because this link is actually 1.6.2 code instead of 1.6.3? https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.js

**Comment by Adns** [comment]
Thanks you for your research about my problem.

Unminified doesn't solve the problem on my side and the file "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.js" doesn't work on IE8-IE7.

The manual update doesn't work too but he gave me an idea. I try to call refresh function 2 times and it's works.

Maybe looking on that way ?

**Comment by caseyjhol** [comment]
I'm not able to replicate this issue in the latest version. If somebody else is able to replicate and link to a demo, I'll reopen.
