### ISSUE TITLE
Space between text and dropdown arrow

### ISSUE THREAD

**Issue by maduhaime** [silviomoreto/bootstrap-select#9]
I noticed that there is not enough space between the text and the arrow. Could you add a little?

**Comment by vlsg** [comment]
I have version 1.11.2 of bootstrap-select and I also have this problem.  I attempted all of the css changes you suggested on 11/23/12 but none of them worked.  Since no doubt a lot has changed in the past 5 yrs, do you have updated advice about how to make the button "title" not overlap the bs-caret?  TIA

**Comment by etlel** [comment]
The space are absent for input-group-lg and input-group-sm classes, so I added the following:

`.input-group-lg .bootstrap-select .filter-option{
	padding-right:10px;
}`

`.input-group-sm .bootstrap-select .filter-option{
	padding-right:15px;
}`

**Comment by vivek-kandhvar** [comment]
This issue is seen again in 1.13.16. Is anyone aware of this yet?
