### ISSUE TITLE
the destroy method should destroy the select element too?

### ISSUE THREAD

**Issue by victorwpbastos** [silviomoreto/bootstrap-select#968]

**Comment by razmo** [comment]
I have this problem when i destroy an instance of selectpicker.
I think that the destroy method should only destroy all elements (div, span, class), events ...etc added when create selectpicker but not remove the select. It's a cleanup method.

**Comment by caseyjhol** [comment]
I agree. I think the current `destroy()` implementation is incorrect, and most people would probably expect it to only destroy the bootstrap-select instance, and not the select element itself. I guess for backwards compatibility, we could call something like 
```javascript
$('.selectpicker').selectpicker('destroy', true);
```
 to keep the select element instead of removing it?

**Comment by jacobbroberg** [comment]
I think this relates to the issue I created a while ago: #1143
My issue is not so much that the original select is left hidden, but that the bootstrap select div is left visible

**Comment by himdel** [comment]
Just ran into the problem. The expected behaviour for destroy should definitely be to remove just the added elements and not the select element itself - that's what all jquery-ui widgets do. Whether it remains hidden or not.. I think if `.selectpicker()` added the class it should remove it, but if not, not.

@caseyjhol I think `.selectpicker('destroy')` should do the right thing, backwards compatibility is overrated if everybody else is doing it the other way around :). If `,selectpicker('destroy', true)` removes the select, why not, but I'm not sure if any people actually depend on that..

**Comment by OpakAlex** [comment]
```
$(document).on('turbolinks:before-cache', function() {
  $('.selectpicker').each(function(index, el){
    const $picker = $(el);
    const picker = $picker.data('selectpicker');
    if (picker) {
        picker.destroy();
        $picker.addClass('selectpicker');
    }
  });
});
```
